global:
  scrape_interval: 15s

scrape_configs:
  - job_name: uptime-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8008"]

  - job_name: uptime-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:8009"]

